project 'TestRappi.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TestRappi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestRappi

  target 'TestRappiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestRappiUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'ObjectMapper', '~> 3.4'
  pod "youtube-ios-player-helper", "~> 0.1.4"
  pod 'youtube-ios-player-helper-swift'
  
end
